banned_words = [
  "was", "were", "had", "did", "said", "made", "went", "took", "came", "saw", "pickled",
  "knew", "got", "gave", "found", "thought", "told", "became", "left", "felt",
  "put", "brought", "began", "kept", "held", "wrote", "stood", "heard", "let",
  "meant", "set", "met", "ran", "paid", "sat", "spoke", "lay", "led", "read",
  "grew", "lost", "fell", "sent", "built", "understood", "drew", "broke",
  "spent", "sold", "bought", "cut", "hit", "shut", "hurt", "caught", "taught",
  "fought", "sought", "dealt", "won", "hung", "fed", "bit", "threw", "drove",
  "flew", "chose", "forgot", "froze", "hid", "rode", "rose", "shook", "shot",
  "slept", "slid", "stole", "struck", "swam", "swore", "swept", "tore", "woke",
  "wore", "wound", "sang", "sank", "rang", "drank", "shrank", "sprang", "stank",
  "ate", "beat", "blew", "bore", "bound", "bred", "cast", "clung", "crept",
  "dug", "dove", "fled", "flung", "forbade", "forgave", "forsook", "ground",
  "knelt", "knit", "leapt", "lent", "lit", "quit", "shed", "shone", "shrunk",
  "slit", "slung", "slunk", "sown", "spat", "sped", "spun", "split", "spread",
  "sprung", "stung", "strode", "strung", "stuck", "stunk", "swung", "thrust",
  "trod", "underwent", "upheld", "wept", "wrung",
  "walked", "talked", "jumped", "played", "worked", "called", "asked", "helped",
  "wanted", "needed", "started", "finished", "opened", "closed", "watched",
  "listened", "looked", "tried", "used", "moved", "changed", "turned", "learned",
  "showed", "followed", "believed", "seemed", "appeared", "happened", "continued",
  "created", "decided", "expected", "included", "involved", "lived", "loved",
  "named", "offered", "passed", "picked", "placed", "planned", "pointed",
  "produced", "provided", "pulled", "pushed", "reached", "received", "remained",
  "remembered", "reported", "required", "returned", "served", "stopped", "studied",
  "suggested", "supported", "touched", "traveled", "waited", "wondered", "acted",
  "added", "admitted", "agreed", "allowed", "answered", "arrived", "attached",
  "attacked", "attempted", "attended", "avoided", "backed", "baked", "balanced",
  "banned", "based", "bathed", "belonged", "blamed", "blocked", "booked", "bored",
  "borrowed", "bothered", "bounced", "breathed", "brushed", "burned", "buried",
  "calculated", "calmed", "camped", "canceled", "captured", "cared", "carried",
  "caused", "celebrated", "challenged", "chased", "chatted", "cheated", "checked",
  "cheered", "claimed", "cleaned", "cleared", "climbed", "clipped", "coached",
  "coated", "coded", "collected", "colored", "combined", "comforted", "commanded",
  "commented", "communicated", "compared", "competed", "complained", "completed",
  "complicated", "composed", "concerned", "concluded", "condemned", "conducted",
  "confessed", "confirmed", "confused", "congratulated", "connected", "considered",
  "consisted", "constructed", "contained", "contributed", "controlled", "convinced",
  "cooked", "cooled", "copied", "corrected", "coughed", "counted", "covered",
  "cracked", "crashed", "crawled", "crossed", "crowded", "crushed", "cried",
  "cured", "curled", "cycled", "damaged", "danced", "dared", "dated", "deceived",
  "delivered", "demanded", "denied", "depended", "deposited", "described",
  "deserved", "designed", "desired", "destroyed", "detected", "determined",
  "developed", "devoted", "dialed", "differed", "directed", "disagreed",
  "disappeared", "discovered", "discussed", "disliked", "dismissed", "displayed",
  "distributed", "disturbed", "divided", "doubled", "doubted", "downloaded",
  "dragged", "drained", "dreamed", "dressed", "dried", "drilled", "dripped",
  "dropped", "drowned", "dumped", "dusted", "earned", "echoed", "edited",
  "educated", "eliminated", "embarrassed", "emerged", "employed", "emptied",
  "enabled", "encountered", "encouraged", "ended", "engaged", "engineered",
  "enhanced", "enjoyed", "ensured", "entered", "entertained", "escaped",
  "established", "estimated", "evaluated", "examined", "exceeded", "exchanged",
  "excited", "exclaimed", "excused", "executed", "exercised", "existed", "expanded",
  "experienced", "experimented", "explained", "exploded", "explored", "exported",
  "exposed", "expressed", "extended", "faced", "faded", "failed", "fainted",
  "fancied", "farmed", "fascinated", "fastened", "faxed", "feared", "feasted",
  "featured", "fetched", "filed", "filled", "filmed", "filtered", "financed",
  "fired", "fitted", "fixed", "flapped", "flashed", "floated", "flooded", "flowed",
  "folded", "fooled", "forced", "formed", "founded", "framed", "freed", "fried",
  "frightened", "frustrated", "fulfilled", "functioned", "gained", "gathered",
  "gazed", "generated", "gestured", "giggled", "glanced", "glowed", "grabbed",
  "graduated", "granted", "grasped", "greeted", "grieved", "grilled", "grinned",
  "gripped", "groaned", "grouped", "guaranteed", "guarded", "guessed", "guided",
  "handed", "handled", "hanged", "harmed", "harvested", "hated", "headed", "healed",
  "heated", "hesitated", "highlighted", "hired", "hopped", "hoped", "hosted",
  "hugged", "hummed", "hunted", "hurried", "identified", "ignored", "illustrated",
  "imagined", "imitated", "immigrated", "impacted", "implemented", "implied",
  "imported", "imposed", "impressed", "improved", "increased", "indicated",
  "influenced", "informed", "inherited", "injured", "inserted", "inspected",
  "inspired", "installed", "instructed", "insured", "intended", "interested",
  "interpreted", "interrupted", "interviewed", "introduced", "invaded", "invented",
  "invested", "investigated", "invited", "irritated", "isolated", "issued",
  "itched", "jammed", "joked", "journeyed", "judged", "juggled", "jumped", "kicked",
  "killed", "kissed", "kneeled", "knocked", "labeled", "lacked", "landed", "lasted",
  "laughed", "launched", "leaked", "leaned", "lifted", "liked", "limited", "linked",
  "listed", "loaded", "located", "locked", "logged", "longed", "lowered", "lunched",
  "maintained", "managed", "manufactured", "mapped", "marched", "marked", "marketed",
  "married", "mashed", "masked", "matched", "measured", "meditated", "melted",
  "memorized", "mentioned", "merged", "messaged", "minded", "minimized", "missed",
  "mixed", "modeled", "modified", "monitored", "mopped", "motivated", "mourned",
  "multiplied", "murdered", "nailed", "narrated", "navigated", "needed", "negated",
  "neglected", "negotiated", "nested", "networked", "nodded", "nominated", "noted",
  "noticed", "numbered", "nursed", "obeyed", "objected", "obligated", "observed",
  "obtained", "occupied", "occurred", "offended", "operated", "opposed", "opted",
  "optimized", "ordered", "organized", "originated", "outlined", "overheard",
  "overlooked", "owed", "owned", "packed", "padded", "painted", "paired", "panicked",
  "paraded", "paralyzed", "parked", "participated", "partnered", "patched", "patted",
  "paused", "peeked", "peeled", "performed", "permitted", "persuaded", "phoned",
  "photographed", "pinched", "pitched", "plagued", "planted", "pleased", "pledged",
  "plotted", "plugged", "plunged", "poked", "polished", "polled", "pondered",
  "popped", "posed", "positioned", "possessed", "posted", "postponed", "poured",
  "practiced", "praised", "predicted", "preferred", "prepared", "prescribed",
  "presented", "preserved", "presided", "pressed", "pretended", "prevented",
  "priced", "printed", "prioritized", "proceeded", "processed", "proclaimed",
  "programmed", "progressed", "prohibited", "projected", "promised", "promoted",
  "pronounced", "proposed", "prosecuted", "protected", "protested", "proved",
  "published", "pumped", "punched", "punished", "purchased", "pursued", "qualified",
  "questioned", "quoted", "raced", "rained", "raised", "ranked", "rated", "reacted",
  "realized", "reasoned", "recalled", "recognized", "recommended", "recorded",
  "recovered", "recruited", "recycled", "reduced", "referred", "reflected",
  "reformed", "refreshed", "refused", "registered", "regretted", "regulated",
  "rejected", "related", "relaxed", "released", "relied", "relieved", "reloaded",
  "remarked", "remedied", "reminded", "removed", "renamed", "rendered", "renewed",
  "rented", "repaired", "repeated", "replaced", "replied", "requested", "rescued",
  "researched", "reserved", "resigned", "resisted", "resolved", "respected",
  "responded", "rested", "restored", "restricted", "resulted", "resumed", "retained",
  "retired", "retrieved", "revealed", "reviewed", "revised", "rewarded", "risked",
  "roasted", "robbed", "rocked", "rolled", "rotated", "rubbed", "ruined", "ruled",
  "rushed", "sacrificed", "saddened", "sailed", "sampled", "satisfied", "saved",
  "scanned", "scared", "scattered", "scheduled", "scored", "scratched", "screamed",
  "screened", "scrolled", "scrubbed", "sealed", "searched", "seasoned", "seated",
  "secured", "selected", "separated", "served", "settled", "sewed", "shaded",
  "shaped", "shared", "shattered", "shaved", "sheltered", "shifted", "shipped",
  "shocked", "shopped", "shortened", "shouted", "shoveled", "showered", "shredded",
  "shrieked", "shrugged", "shuffled", "signaled", "signed", "simplified",
  "simulated", "sinned", "sipped", "situated", "sized", "sketched", "skied",
  "skipped", "slammed", "slapped", "sliced", "slipped", "slowed", "smashed",
  "smelled", "smiled", "smoked", "smoothed", "snapped", "sneaked", "sneezed",
  "sniffed", "snored", "soaked", "solved", "sorted", "sounded", "sparked", "spawned",
  "speculated", "spelled", "spied", "spilled", "spoiled", "sponsored", "spotted",
  "sprayed", "squeezed", "stacked", "staffed", "staged", "stained", "stamped",
  "stared", "stated", "stationed", "stayed", "steered", "stepped", "stiffened",
  "stimulated", "stirred", "stitched", "stocked", "stomped", "stored", "stormed",
  "straightened", "strained", "stranded", "strangled", "strapped", "streamed",
  "strengthened", "stressed", "stretched", "stripped", "strived", "stroked",
  "struggled", "stuffed", "stumbled", "stunned", "submitted", "subscribed",
  "substituted", "subtracted", "succeeded", "sucked", "suffered", "summoned",
  "supervised", "supplied", "supposed", "surfaced", "surfed", "surprised",
  "surrendered", "surrounded", "surveyed", "survived", "suspected", "suspended",
  "sustained", "swallowed", "swapped", "switched", "symbolized", "sympathized",
  "tackled", "tagged", "talked", "tamed", "tapped", "targeted", "tasted", "taxed",
  "teased", "telephoned", "tempted", "terminated", "terrified", "tested",
  "testified", "thanked", "thickened", "threatened", "thrilled", "thrived",
  "ticked", "tickled", "tied", "tightened", "tilted", "timed", "tipped", "tired",
  "titled", "toasted", "tolerated", "topped", "tortured", "tossed", "totaled",
  "touched", "toured", "traced", "tracked", "traded", "trained", "transferred",
  "transformed", "translated", "transmitted", "transported", "trapped", "treasured",
  "treated", "trembled", "tricked", "triggered", "trimmed", "tripled", "triumphed",
  "troubled", "trusted", "tumbled", "tuned", "twisted", "typed", "uncovered",
  "underlined", "undermined", "undertook", "undressed", "unfolded", "unified",
  "united", "unlocked", "unpacked", "unraveled", "unveiled", "updated", "upgraded",
  "uploaded", "urged", "utilized", "vacationed", "validated", "valued", "vanished",
  "varied", "ventured", "verified", "viewed", "violated", "visited", "visualized",
  "voiced", "volunteered", "voted", "vowed", "wandered", "warmed", "warned",
  "washed", "wasted", "watered", "waved", "weakened", "weathered", "weighed",
  "welcomed", "whispered", "whistled", "widened", "wiped", "wished", "withdrawn",
  "witnessed", "wobbled", "woken", "wondered", "worried", "worshipped", "wounded",
  "wrapped", "wrecked", "wrestled", "wrinkled", "yawned", "yelled", "yielded",
  "zapped", "zipped", "zoomed"
]
